;AVERAGE AND SUM 
MOV [2000H],06H;N=6
MOV SI,2000H
MOV CL,[SI];DECLARE N IN 2000H MEMORY
MOV CH,00H
MOV BX,CX
MOV AX,0000H
L2:INC SI
INC SI
ADD AX,[SI]
JNC L1; JUMP IF NO CARRY
INC CH
L1:DEC CL
JNZ L2;JUMP IF NO ZERO
INC SI
INC SI
MOV [SI],AX;SUM IS STORED IN 2004H MEMORY
INC SI
INC SI
MOV [SI],CH
MOV DL,CH
MOV DH,00H
DIV BX;DX-AX
INC SI
INC SI
MOV [SI],AX
INC SI
INC SI
MOV [SI],DX; RESULT 
HLT